emel - generate HTML with CSS-like selectors
============================================

emel is an erlang module that allows to generate complex HTML (or XML) using
a syntax that is similar to CSS selectors.

emel is inspired by zen-coding: https://code.google.com/p/zen-coding/

get it
------

::

    git clone https://github.com/marianoguerra/emel

build it
--------

::

    cd emel
    ./rebar compile

test it
-------

::

    ./rebar eunit

use it
------

::

    1> emel:gen("span[type=\"text\"]#asd.foo.bar.baz").
    {ok,"<span id=\"asd\" class=\"foo bar baz\" type=\"text\"/>"}

    2> {ok, S} = emel:gen("span[type=\"text\"]#asd.foo.bar.baz").  
    {ok,"<span id=\"asd\" class=\"foo bar baz\" type=\"text\"/>"}

    3> io:format("~s~n", [S]).
    <span id="asd" class="foo bar baz" type="text"/>
    ok

    
author
------

Mariano Guerra

license
-------

BSD (+ optional beer to the author)
